language: python
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.8.7
install:
  - pip install -q pylint Django==$DJANGO_VERSION djangorestframework factory-boy
script: python -m unittest discover -s tests
